# Deployment step for Woodpecker CI/CD
# No volumes - Suited for deployments without local databases (i.e. external PostgreSQL instance)

steps:
  - name: deploy
    image: alpine:latest
    environment:
      SSH_HOST:
        from_secret: SSH_HOST
      PROJECT_DIRECTORY:
        from_secret: PROJECT_DIRECTORY
      SSH_KEY:
        from_secret: SSH_KEY
      REGISTRY_IMAGE_TAG:
        from_secret: REGISTRY_IMAGE_TAG
      DOCKER_COMPOSE_URL:
        from_secret: DOCKER_COMPOSE_URL
    commands:
      - apk add openssh
      - mkdir -p /root/.ssh/
      - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
      - ssh "$SSH_HOST" "
        cd "$PROJECT_DIRECTORY";
        docker-compose down;
        docker image rm "$REGISTRY_IMAGE_TAG" || true;
        wget -O "$DOCKER_COMPOSE_URL" docker-compose.yml;
        docker pull "$REGISTRY_IMAGE_TAG";
        docker-compose up -d;
        docker image prune -af;
        sleep 60;
        docker-compose logs;"
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: SERVICE_QUEUE_DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: SERVICE_QUEUE_DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          ✅ [{{repo.name}}] Successful deployment for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{else}}
          ❌ [{{repo.name}}] Failed deployment for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{/success}}
    when:
      status: [ success, failure ]

when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - build
