labels:
  platform: linux/amd64

steps:
  - name: test
    image: node:25-alpine3.22
    commands:
      - npm install -g @usebruno/cli --cache /tmp/.npm --prefer-offline
      - sleep 10
      - cd .bruno/goapi && bru run --env goapi.docker
    volumes:
      - /tmp/.npm:/tmp/.npm
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          ✅ [{{repo.name}}] Successful test for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{else}}
          ❌ [{{repo.name}}] Failed test for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{/success}}
    when:
      status: [ success, failure ]
      
when:
  - branch: master
    event:
      - push
      - manual
      - pull_request

depends_on:
  - build

services:
  api:
    image: git.06222001.xyz/keannu125/goapi:latest
    environment:
      SQLITE_DB: "/tmp/db.sqlite3"
    commands:
      - cd /app
      - ./main
    ports:
      - "8000"

      