steps:
  - name: bruno_tests
    image: node:25-alpine3.22
    commands:
      - npm install -g @usebruno/cli --cache /tmp/.npm --prefer-offline
      - echo "Running development tests"
      - cd .bruno 
      - bru run --env goapi.dev
    volumes:
      - /tmp/.npm:/tmp/.npm
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          ✅ [{{repo.name}}] Successful test for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{else}}
          ❌ [{{repo.name}}] Failed test for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{/success}}
    when:
      status: [ success, failure ]
      
when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - deploy_ephemeral