matrix:
  BRUNO_TEST_DIR:
    - books
    - hello

steps:
  - name: run pre-deployment tests
    image: ghcr.io/usebruno/cli:3.5.1-alpine
    commands:
      - cd .bruno
      - sleep 10
      - bru run --env goapi.docker $BRUNO_TEST_DIR
      
when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - build

services:
  api:
    image: git.06222001.xyz/keannu125/goapi:latest
    commands:
      - cd /app
      - ./main